#!/usr/bin/env bash
git config --local user.name "VanDerCat"
git config --local user.email "wandercat@gmail.com"
git config --local core.sshCommand "ssh -i .ssh/id_rsa"
git config --local core.editor "nano"

git push -f